#!/bin/bash
set -euo pipefail
IFS=$'\n\t'
trap 'echo >&2 FATAL ERROR EXIT CODE $? AT $0:$LINENO' ERR

mvn package

# run using maven exec plugin: https://www.baeldung.com/maven-java-main-method
mvn compile exec:java -Dexec.mainClass="com.paulfrischknecht.jnamavendemo.App"

